[package]
name = "rust-mqtt-to-kafka"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.2.4"
kafka = "0.9.0"
paho-mqtt = "0.12.0"
openssl = { version = "0.10.35", features = ["vendored"] }

